### PR TITLE
BACK-943: Integrate Camelot

### PR DESCRIPTION
**Pull request by aburkut**
The PR is based on the changes from @0xpercival's PR https://github.com/paraswap/paraswap-dex-lib/pull/241

### Description from the original PR:

> Camelot is a mix of UniswapV2 and Solidly AMM, with a custom fees implementation.
We're deployed on Arbitrum, here is our live factory: [CamelotFactory](https://arbiscan.io/address/0x6eccab422d763ac031210895c81787e87b43a652)

> This router has been deployed especially for Paraswap integration: [CamelotRouter](https://arbiscan.io/address/0x1Be46c7A40906c19d91d07B3AE69Ef5893268F25)
We've forked it from the router used by all Solidly fork on Optimisim: [SolidlyRouter](https://optimistic.etherscan.io/address/0xa2f581b012E0f2dcCDe86fCbfb529f4aC5dD4983)

> The simple swap method seems to work well.
However, stables does not seem to work for the multiswap method, and I didn't find any Paraswap Solidly adapter for this.

### Summary of the changes:

- [x] improved e2e tests for  `Camelot` https://github.com/paraswap/paraswap-dex-lib/pull/324#issuecomment-1458162121
- [x] deployed the changes to Testing env
- [x] run tests against Testing API  https://github.com/paraswap/paraswap-dex-lib/pull/324#issuecomment-1458235698
- [x] manual testing on Testing env https://github.com/paraswap/paraswap-dex-lib/pull/324#issuecomment-1458246901

cc @0xpercival

### CODE REVIEW

**Comment by aburkut** [comment]
Camelot integration tests results:

paraswap-dex-lib – camelot-integration test ts 2023-03-07 15-35-30

**Comment by aburkut** [comment]
Camelot e2e tests on Arbitrum chain:

paraswap-dex-lib – camelot-e2e test ts 2023-03-07 16-19-38

**Comment by aburkut** [comment]
Camelot e2e tests on Arbitrum chain against Orders API: 
paraswap-dex-lib – camelot-e2e test ts 2023-03-07 17-06-25

**Comment by aburkut** [comment]
Manual testing on Test env:

ParaSwap - Solving Liquidity for DeFi 🔊 2023-03-07 17-12-03

ParaSwap - Solving Liquidity for DeFi 🔊 2023-03-07 17-12-15

--- 

ParaSwap - Solving Liquidity for DeFi 🔊 2023-03-07 17-09-23

ParaSwap - Solving Liquidity for DeFi 🔊 2023-03-07 17-09-36

---

ParaSwap - Solving Liquidity for DeFi 🔊 2023-03-07 17-10-34

ParaSwap - Solving Liquidity for DeFi 🔊 2023-03-07 17-10-47

**Review by paraschiv-razvan-toptal — APPROVED** [review]

**Pull request merged**
