### PR TITLE
integrate babydogeswap

### PR DESCRIPTION
**Pull request by itdev-1210**
Website: https://babydogeswap.com/
Docs: https://baby-doge-coin.gitbook.io/babydoge-docs/

### CODE REVIEW

**Comment by itdev-1210** [comment]
Hi, @ColonelJ 
Can you please review our PR?

This is for BabyDogeSwap.

**Comment by ColonelJ** [comment]
Hi, this looks like a fork of UniswapV2, instead of copying the code you can simply add your DEX to the existing config.ts of uniswap-v2, you can see we already have a lot of forks listed.  If there's anything slightly different/special in your smart contract implementation which isn't already covered by the config (e.g. individual pool fees), you could instead extend the UniswapV2 class into another file inside uniswap-v2 with the config inside (there are some examples of that too).  Obviously, if you can add your DEX with only config that is far preferable for us.  Thanks!

**Comment by itdev-1210** [comment]
Hi, Thank you for the feedback.
We are forking Uniswap-V2.
so, just only add config like pancakeswap?

**Comment by itdev-1210** [comment]
Remake.

**Pull request closed without merging**
