### PR TITLE
add AvadexV3

### PR DESCRIPTION
**Pull request by avadex**

### CODE REVIEW

**Comment by shresthagrawal** [comment]
@avadex This doesn't seem to be the correct implementation. Please refer to https://github.com/paraswap/paraswap-dex-lib#readme to learn about adding DEX

**Comment by shresthagrawal** [comment]
@avadex This doesn't seem to be the correct implementation. Please refer to https://github.com/paraswap/paraswap-dex-lib#readme to learn about adding DEX

**Comment by avadex** [comment]
> @avadex This doesn't seem to be the correct implementation. Please refer to https://github.com/paraswap/paraswap-dex-lib#readme to learn about adding DEX

do you have test files for uniswap v3 I can look into?

**Comment by avadex** [comment]
> @avadex This doesn't seem to be the correct implementation. Please refer to https://github.com/paraswap/paraswap-dex-lib#readme to learn about adding DEX

do you have test files for uniswap v3 I can look into?

**Pull request closed without merging**
