### PR TITLE
BACK-1685: Integrate UsualBond

### PR DESCRIPTION
**Pull request by JackieJoo**

### CODE REVIEW

**Comment by 0xAurelou** [comment]
Hello,
I have few questions:

- The first one, on the screen attached you will see that I have some 2e2 test failling I don't understand why there is some test related to this. In my case I am adding a route from USD0 (stablecoin) to USD0++ (our stacking token) to redirect user on Primary market when needed. In no case I "care" about the pricing of ETH -> USD0 and USD0 -> ETH. Also this 2 routes are working well on paraswap app so I don't understand where is the issue and why there is one.
image
image
image

- Second question  on my integration, I have this error 
```
    Returned error: execution reverted: revert: Multicall aggregate: call failed
```

I found this one pretty weird, first I thought the calldata on my call was wrong, a console log of the calladata display this
```
at getReaderCalldata (src/dex/usual-bond/usual-bond-integration.test.ts:43:11)

  console.log
    [
      {
        target: '0x35d8949372d46b7a3d5a56006ae77b215fc69bc0',
        callData: '0xa0712d680000000000000000000000000000000000000000000000000de0b6b3a7640000'
      }
    ]
```

This calldata is correct, to be sure you can check the following tx of mint on Etherscan: https://etherscan.io/tx/0x2f615fd0d2f7dd01b9ca286515eb37d0a281f3dd49d74ea3ae15946554d9b2c3
The target contract is good and the amount is correct. Any idea where this can come from ?

Have a nice day

**Comment by 0xAurelou** [comment]
@JackieJoo ping for visibility 🏓

**Comment by JackieJoo** [comment]
> Hello, I have few questions:
> 
> * The first one, on the screen attached you will see that I have some 2e2 test failling I don't understand why there is some test related to this. In my case I am adding a route from USD0 (stablecoin) to USD0++ (our stacking token) to redirect user on Primary market when needed. In no case I "care" about the pricing of ETH -> USD0 and USD0 -> ETH. Also this 2 routes are working well on paraswap app so I don't understand where is the issue and why there is one.
> 
> image image image
> * Second question  on my integration, I have this error
> 
> ```
>     Returned error: execution reverted: revert: Multicall aggregate: call failed
> ```
> 
> I found this one pretty weird, first I thought the calldata on my call was wrong, a console log of the calladata display this
> 
> ```
> at getReaderCalldata (src/dex/usual-bond/usual-bond-integration.test.ts:43:11)
> 
>   console.log
>     [
>       {
>         target: '0x35d8949372d46b7a3d5a56006ae77b215fc69bc0',
>         callData: '0xa0712d680000000000000000000000000000000000000000000000000de0b6b3a7640000'
>       }
>     ]
> ```
> 
> This calldata is correct, to be sure you can check the following tx of mint on Etherscan: https://etherscan.io/tx/0x2f615fd0d2f7dd01b9ca286515eb37d0a281f3dd49d74ea3ae15946554d9b2c3 The target contract is good and the amount is correct. Any idea where this can come from ?
> 
> Thanks in advance
> 
> Have a nice day

First question - you just need to delete [these lines](https://github.com/paraswap/paraswap-dex-lib/pull/775/files#diff-25b4a5bf7666a73424a83c1acbab75bab7d6932b4e5560e2e5be55e57f739a95R81-R106), where we test for native swaps, it's just typical way of checking integration (native -> erc20, erc20 -> native, erc20 -> erc20), if your integration doesn't support it - feel free to remove non-needed tests

Second question - to get a better understanding of the failure, you can run your tx in tenderly with calldata you generated

Screenshot 2024-09-09 at 23 48 00

In integration tests we don't try to perform a swap(`mint`), but rather compare the pricing you produce off-chain and on-chain (on-chain meaning by calling a contract method that returns rate, e.g. `getAmountOut`, etc)

**Comment by 0xAurelou** [comment]
> In integration tests we don't try to perform a swap(mint), but rather compare the pricing you produce off-chain (getPricesVolume call) and on-chain (by calling a contract method that returns rate, e.g. getAmountOut, preview etc)

I think that's a big problem for us since we don't return anything in the function. We assume that the inputAmount is the outputAmount and the only way for us is to access the event.
Is this a huge problem for Paraswap ?

**Review by 0xNazarii — APPROVED** [review]

**Pull request merged**
